config/routes.rb
Mebay::Application.routes.draw do
  resources :ads
  get 'ads/:id' => 'ads#show'

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

	def index
		@ads = Ad.all
	end	

	def show
		@ad = Ad.find(params[:id])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/index.html.erb
<h2>Anúncios</h2>
<table class="table table-striped table-bordered">
	
	<thead>
		<tr>
			<th>Nome do anúncio</th>
			<th>Operações</th>
		</tr>
	</thead>
	<tbody>
		<% @ads.each do |ad| %>
			<tr>
				<td><%= ad.name %></td>
				<td><%= link_to 'Visualizar anúncio', ad %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/ads/show.html.erb
        <h3>Detalhes do anúncio</h3>
        <p>
        	<strong>Nome:</strong>  <%= @ad.name %>
        </p>
        <p>
        	<strong>Descrição:</strong></br>
        	 <%= @ad.description %>
        </p>
        <p>
        	<strong>Preço:</strong> <%= @ad.price %>
        </p>
        <p>
        	<strong>ID do Vendedor:</strong>  <%= @ad.seller_id %>
        </p>
        <p>
        	<strong>E-mail:</strong>  <%= @ad.email %>
        </p>
        <p>
        	<img src="<%= @ad.img_url %>" alt="<%= @ad.name %>" class="media" />
        </p>
        <%= link_to 'Voltar', ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeBay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>